application: kexprdio
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: kexprdio.app
  
- url: /style
  static_dir: style
  
#- url: /img
#  static_dir: img
  
- url: /js
  static_dir: js
  
- url: /lib
  static_dir: lib

libraries:
- name: webapp2
  version: "2.5.1"
# builtins:
# - appstats: on
# - deferred: on
# - remote_api: on
