application: kexprdio
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: kexprdio.app
  
- url: /index\.html
  script: home.app

# builtins:
# - appstats: on
# - deferred: on
# - remote_api: on
